### ISSUE TITLE
Proposal: Folder structure for folders

### ISSUE THREAD

**Issue by nfode** [nfode/TOSCAna#3]
I propose the following structure:
- `docs/user/` - for the user docs
- `docs/dev/` - for all the dev related docs

What do you think?

**Comment by mmunozba** [comment]
Better structure always sounds good. What exactly do you mean with user docs?

**Comment by nfode** [comment]
All the user related documents, like how to install, setup and use.

**Comment by c-mueller** [comment]
Another option could be the wiki feature that is supported by a GitHub Repository.

But the suggested folder structure seems good.

We also have to decide, how the Web UI will be kept in the same repo. Because ng-Apps cannot be built using Maven (at least i think so)

**Comment by nfode** [comment]
It is not possible to create PRs for the GitHub wiki! Thats a problem...

**Comment by nfode** [comment]
I think TravisCi can build different languages. But we have look into this. The winery project might have a solution. I created a issue for this ([#10](https://github.com/nfode/TOSCAna/issues/10)).

**Comment by mmunozba** [comment]
This folder structure has been implemented.
