### ISSUE TITLE
Clarify status of java datamodel of yaml tosca spec

### ISSUE THREAD

**Issue by hnicke** [nfode/TOSCAna#5]
Will we get a java datamodel of the TOSCA YAML spec (simple profile) or do we have to implement it ourselves?
Will we have to write our own yaml2java parser?

**Comment by hnicke** [comment]
We will soon (in some days) get access to the java datamodel of the TOSCA YAML spec and a parser,
so we don't have to implement it ourselves.

**Comment by mmunozba** [comment]
Data model is available here https://github.com/kleinech/winery/tree/tosca_yaml_model
Parser is apparently coming soon.
