### ISSUE TITLE
 Clarify version of Angular

### ISSUE THREAD

**Issue by hnicke** [nfode/TOSCAna#7]
Client requested Angular 2.0 as a requirement. 
Angulars newest version right now is 4.
We have to clarify if it's ok to use the latest version.

**Comment by nfode** [comment]
Also important there are two major Angular releases until march 2018. Version 5 in September 2017 and Version 6 in March 2018. Should we at least keep up with Version 5?

Source: [Link](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md)

**Comment by hnicke** [comment]
Keeping up with version 5 might be useful:
- long term support with version 4 is only granted till October '18
- we might be able to postpone work on web app till September/October '17 (release of Angular 5)

At least we should aim for the current version (4) in order to benefit from long term support.

**Comment by c-mueller** [comment]
This has been clarified by the supervisor. The latest version of Angular will be used.
