### ISSUE TITLE
Choose UML tool

### ISSUE THREAD

**Issue by hnicke** [nfode/TOSCAna#9]
Any idea which uml tool we could use?
We'll soon be in the need of creating our first architectural drafts.
For now, we need at least support for:
- Class Diagram
- Component Diagram

I'd propose Visual Paradigm (theres a free [Community Edition](https://www.visual-paradigm.com/download/community.jsp), as I've already worked wih it and liked it.

**Comment by nfode** [comment]
You meant to write Visual Paradigm? (Visual Studio is by Microsoft)
My favorite tool at the moment is draw.io but I am okay with Visual Paradigm

**Comment by hnicke** [comment]
While prototyping I've used draw.io and it was a pain.

**Comment by mmunozba** [comment]
The only tool I ever used was [UMLet](http://www.umlet.com/) which is open-source and multi-platform.
But I'd gladly switch to a more comfortable alternative since UMLet takes some getting used to.

**Comment by mmunozba** [comment]
Suggestion from the supervisors:
- [Plant UML](http://plantuml.com)
- Microsoft Visio (available through [Microsoft Imagine](http://www.stud.uni-stuttgart.de/dienste/software/msimagine.html) for students)
- [draw.io](https://www.draw.io) (already mentioned by @nfode)
- [Lucidchart](https://www.lucidchart.com/pages/de)

**Comment by c-mueller** [comment]
Just to give my opinion:

- **Visio** requires Windows. That might be a problem. 
- **draw.io** is decent for simple diagrams but as they get complex its a pain.
- **UMLet** was never used by me, however its free and probably Open Source, and therefore no further Licensing is needed.
- **Lucidchart** seems to be very nice, however it requires a paid account for non educational purposes. After googling a bit i found a signup page for education accounts: [here](https://www.lucidchart.com/users/education/registerLevel?tP=1&t10=A)
- **PlantUML** might be nice to review the changes without opening a special tool
- **Visual Paradigm** i never saw this tool before so i don't know anything about it.

**Comment by orferch** [comment]
- **UMLet** is a bit strange to work with

- **Visual Paradigm** quite liked it, but I think we would need a License from the University or just the 30 days trial if it's enough

- never used the others

**Comment by mmunozba** [comment]
I tested out all of the suggested tools and have come up with these conclusions:
These tools are not fit for our project:
- **Microsoft Visio** - Only available on Windows
- **Visual Paradigm** - As far as I can tell, there are no student versions of Visual Paradigm. The Community edition adds watermarks to all diagrams which is not something that I would want on our diagrams. 
- **draw.io** - Similar to Lucidchart, but as already mentioned, very difficult to work with complex diagrams.
- **UMLet** - Clunky and unintuitive, other tools are much easier to use and just as if not more powerful.

That leaves us with these:
- **PlantUML** - Seems like a good option, but I personally prefer the graphical creation of diagrams compared to the creation in textual syntax used in PlantUML.
- **Lucidchart** - Easy to use web app (multi-platform!) which is available for students.

Personally, I think **Lucidchart** is the best solution for us.

**Comment by c-mueller** [comment]
Lucidchart has been chosen!
